name: PR Changelog Addition
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronized
    - labeled
    - unlabeled
jobs:
  add_to_changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: guzzler/hello-github-actions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
